// packages/vue/example/button/button.tsx
import Vue from 'vue'
import { proxyh } from '../proxy-h'
import { CubeButton as UniButton } from '@uni-component/example'
import { uni2Vue } from '../../src'

export const CubeButton = uni2Vue(UniButton, (props, state, { slots }) => {
  const { n, rootClass, clickAction } = state
  const t = props.text ? props.text : slots.default && slots.default()
  return (
    <button class={rootClass} type={props.type} onClick={clickAction}>
      <span>{ t } { n }</span>
    </button>
  )
})

// just for test
const Appp = () => {
  return <CubeButton primary>xxx</CubeButton>
}

// packages/react/example/button/button.tsx
import React from 'react'
import { uni2React } from '../../src'
import { CubeButton as UniButton } from '@uni-component/example'

export const CubeButton = uni2React(UniButton, (props, state, { slots }) => {
  const {
    n,
    rootClass,
    clickAction
  } = state
  const t = props.text ? props.text : slots.default && slots.default()
  return (
    <button className={rootClass} type={props.type} onClick={() => clickAction()}>
      <span>{ `${t} ${n}` }</span>
    </button>
  )
})

// just for test
// const Appp = () => {
//   return <CubeButton primary={false}>xxx</CubeButton>
// }
